import { Species } from "../types";

export const LOCAL_SPECIES_CATALOG: Record<string, Species> = {
  "indian-peafowl": {
    id: "indian-peafowl",
    common_name: "Indian Peafowl",
    scientific_name: "Pavo cristatus",
    family: "Phasianidae",
    order_name: "Galliformes",
    habitat_types: ["Forest", "Agricultural", "Garden", "Grassland"],
    diet: "Omnivorous (seeds, insects, fruits, small reptiles, amphibians)",
    geographic_distribution: "Native to the Indian subcontinent; introduced across Europe, Americas, and Australia.",
    ecological_role: "Terrestrial seed disperser and biological pest controller (consuming crop-damaging insects and venomous snakes).",
    behavior_notes: "Ground-foraging, roosts high in canopy trees at dusk. Males engage in dramatic courtship train fanning accompanied by vocal 'may-awe' calls.",
    identification_features: "Male has iridescent electric blue neck and breast, metallic green-bronze eye-spotted train. Female is mottled brown with white throat and pale belly.",
    conservation_status: "Least Concern (LC)",
    description: "The Indian Peafowl is celebrated for its spectacular iridescent plumage and is India's national bird. Highly adaptable to forest edges and cultivated land.",
    image_url: "/species/indian-peafowl.jpg",
  },
  "white-throated-kingfisher": {
    id: "white-throated-kingfisher",
    common_name: "White-throated Kingfisher",
    scientific_name: "Halcyon smyrnensis",
    family: "Alcedinidae",
    order_name: "Coraciiformes",
    habitat_types: ["Wetland", "Agricultural", "River/Lake", "Garden", "Urban"],
    diet: "Carnivorous (small fish, crabs, frogs, lizards, large insects, earthworms)",
    geographic_distribution: "Resident across the Middle East, Indian subcontinent, Indochina, and Philippines.",
    ecological_role: "Mid-tier predator regulating aquatic and terrestrial insect/amphibian populations across agricultural edges.",
    behavior_notes: "Sits motionless on exposed telephone wires or branches overlooking open ground, plunging swiftly down onto prey.",
    identification_features: "Bright chestnut head and belly, bright white throat and breast shield, turquoise-blue back and wings with black patches, massive coral-red dagger bill.",
    conservation_status: "Least Concern (LC)",
    description: "Unlike many kingfishers, this species frequently hunts far from standing water, thriving in open plains, orchards, and urban gardens.",
    image_url: "/species/white-throated-kingfisher.jpg",
  },
  "great-hornbill": {
    id: "great-hornbill",
    common_name: "Great Hornbill",
    scientific_name: "Buceros bicornis",
    family: "Bucerotidae",
    order_name: "Bucerotiformes",
    habitat_types: ["Forest", "Mountain"],
    diet: "Frugivorous primary (figs, wild nutmeg), supplements with small mammals and birds during breeding.",
    geographic_distribution: "Canopy forests of the Western Ghats and Himalayan foothills through Southeast Asia to Sumatra.",
    ecological_role: "Crucial 'farmer of the forest' — primary disperser of large-seeded climax forest tree species.",
    behavior_notes: "Flies with heavy, roaring wingbeats audible from hundreds of meters. Females seal themselves inside tree cavities to nest while males provision them through a narrow slit.",
    identification_features: "Massive yellow bill surmounted by a U-shaped bright yellow-orange casque; black and white wings with broad white tail crossed by subterminal black band.",
    conservation_status: "Vulnerable (VU)",
    description: "One of the largest arboreal birds in Asian tropical rainforests, vulnerable to habitat fragmentation and ancient tree logging.",
    image_url: "/species/great-hornbill.jpg",
  },
  "red-junglefowl": {
    id: "red-junglefowl",
    common_name: "Red Junglefowl",
    scientific_name: "Gallus gallus",
    family: "Phasianidae",
    order_name: "Galliformes",
    habitat_types: ["Forest", "Agricultural", "Grassland"],
    diet: "Omnivorous (seeds, fallen grain, berries, termites, beetle larvae)",
    geographic_distribution: "Tropical and subtropical forests of India, Nepal, Southeast Asia, and southern China.",
    ecological_role: "Ground seed disperser and soil aerator; wild ancestor of all domestic poultry worldwide.",
    behavior_notes: "Alert and wary; utters a sharp, staccato crow at dawn. Roosts high up in bamboo thickets and forest trees to avoid nocturnal ground predators.",
    identification_features: "Male boasts glorious golden-orange and crimson neck hackles, bright red fleshy comb and wattles, iridescent dark bottle-green sickle tail feathers, and grey legs. Female is cryptically mottled buff-brown.",
    conservation_status: "Least Concern (LC)",
    description: "The magnificent wild ancestor of all domestic chickens, flourishing in secondary tropical forests and bamboo reserves.",
    image_url: "/species/red-junglefowl.jpg",
  },
  "brahminy-kite": {
    id: "brahminy-kite",
    common_name: "Brahminy Kite",
    scientific_name: "Haliastur indus",
    family: "Accipitridae",
    order_name: "Accipitriformes",
    habitat_types: ["Coastal", "Wetland", "River/Lake"],
    diet: "Opportunistic scavenger and predator (carrion, dying fish, crabs, small rodents, insects)",
    geographic_distribution: "Coastal wetlands and estuaries across South Asia, Southeast Asia, and coastal Australia.",
    ecological_role: "Ecosystem scavenger cleaning shoreline debris and regulating estuarine fish and crab mortality.",
    behavior_notes: "Soars along shorelines and harbors with bowed wings, skimming low over tidal flats to seize surface items with talons.",
    identification_features: "Striking contrasting plumage with rich chestnut-red back and wings, immaculate pure white head, neck, and upper breast with fine dark streaks.",
    conservation_status: "Least Concern (LC)",
    description: "A graceful medium raptor often associated with coastal lagoons, mangrove edges, and harbor channels.",
    image_url: "/species/brahminy-kite.jpg",
  },
  "black-crowned-night-heron": {
    id: "black-crowned-night-heron",
    common_name: "Black-crowned Night Heron",
    scientific_name: "Nycticorax nycticorax",
    family: "Ardeidae",
    order_name: "Pelecaniformes",
    habitat_types: ["Wetland", "River/Lake", "Coastal"],
    diet: "Carnivorous (small fish, crustaceans, frogs, aquatic insects, worms)",
    geographic_distribution: "Cosmopolitan wetland resident across North & South America, Europe, Africa, and Asia.",
    ecological_role: "Nocturnal aquatic predator occupying wetland food chains during nighttime when diurnal waders roost.",
    behavior_notes: "Stocky and hunched posture; roosts in dense waterside foliage by day and begins solitary stalking in shallow margins at twilight.",
    identification_features: "Stocky build, black crown and back, pale gray wings and white underparts. Piercing ruby-red eyes, short yellow legs, two long white head plumes during breeding.",
    conservation_status: "Least Concern (LC)",
    description: "A nocturnal ardeid species whose presence indicates healthy riparian reedbeds and functioning wetland ecosystems.",
    image_url: "/species/black-crowned-night-heron.jpg",
  },
  "purple-sunbird": {
    id: "purple-sunbird",
    common_name: "Purple Sunbird",
    scientific_name: "Cinnyris asiaticus",
    family: "Nectariniidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Forest", "Agricultural"],
    diet: "Nectarivore primarily; feeds young on spiders and small caterpillars.",
    geographic_distribution: "Across the Indian subcontinent through Indochina and parts of the Arabian Peninsula.",
    ecological_role: "Vital pollinator for indigenous flowering trees (e.g. Butea monosperma, Erythrina, Woodfordia).",
    behavior_notes: "Hyperactive hovering and darting flight; probes tubular blossoms with downcurved bill while producing rapid buzzing chips.",
    identification_features: "Tiny size (10 cm). Breeding male appears glossy metallic bluish-black with purple sheen and tiny yellow/red pectoral tufts; non-breeding male and female are olive-brown above and pale yellow below.",
    conservation_status: "Least Concern (LC)",
    description: "The Old World ecological equivalent of hummingbirds, indispensable for floral reproduction across arid and garden landscapes.",
    image_url: "/species/purple-sunbird.jpg",
  },
  "barn-owl": {
    id: "barn-owl",
    common_name: "Barn Owl",
    scientific_name: "Tyto alba",
    family: "Tytonidae",
    order_name: "Strigiformes",
    habitat_types: ["Agricultural", "Grassland", "Urban"],
    diet: "Carnivorous (small rodents, shrews, field mice, voles)",
    geographic_distribution: "Found globally across every continent except Antarctica.",
    ecological_role: "Premier biological rodent manager, saving agricultural yields without toxic chemical rodenticides.",
    behavior_notes: "Silent ghost-like flight aided by comb-like serrations on leading flight feathers; asymmetric ear canals permit hunting in complete pitch darkness by sound alone.",
    identification_features: "Distinctive heart-shaped pale facial disc, dark luminous eyes, golden-buff upperparts mottled with delicate grey specks, silky white-to-buff underparts.",
    conservation_status: "Least Concern (LC)",
    description: "A silent nocturnal hunter revered worldwide for pest control yet vulnerable to secondary poisoning from chemical agricultural rodenticides.",
    image_url: "/species/barn-owl.jpg",
  },
  "indian-vulture": {
    id: "indian-vulture",
    common_name: "Indian Vulture",
    scientific_name: "Gyps indicus",
    family: "Accipitridae",
    order_name: "Accipitriformes",
    habitat_types: ["Grassland", "Forest", "Mountain"],
    diet: "Obligate scavenger (carcasses of ungulates, cattle, and large mammals)",
    geographic_distribution: "Endemic to central and peninsular India and southeastern Pakistan.",
    ecological_role: "Crucial keystone sanitation scavenger: consumes decaying carcasses swiftly, preventing the proliferation of lethal pathogens like anthrax, rabies, and botulism.",
    behavior_notes: "Soars effortlessly on massive thermals for hours searching for carcasses with keen eyesight. Nests communally on high, sheer rocky cliffs.",
    identification_features: "Large broad-winged raptor (2-2.3 m wingspan); unfeathered dark blackish head and slender neck, pale yellowish bill, sandy-brown mantle with whitish ruff and pale underwing coverts.",
    conservation_status: "Critically Endangered (CR)",
    description: "One of the most ecologically vital scavengers in the world; underwent catastrophic 99% declines due to veterinary diclofenac poisoning, making conservation monitoring essential.",
    image_url: "/species/indian-vulture.jpg",
  },
  "black-rumped-flameback": {
    id: "black-rumped-flameback",
    common_name: "Black-rumped Flameback",
    scientific_name: "Dinopium benghalense",
    family: "Picidae",
    order_name: "Piciformes",
    habitat_types: ["Forest", "Garden", "Urban", "Agricultural"],
    diet: "Insectivorous (wood-boring beetle larvae, tree ants, pupae)",
    geographic_distribution: "Widespread resident across Pakistan, India, Bangladesh, and Sri Lanka.",
    ecological_role: "Primary forest health guardian: excises wood-boring pests from mature tree bark and excavates nest cavities reused by secondary cavity dwellers.",
    behavior_notes: "Hops jerkily up tree trunks propped on stiff tail feathers, tapping resonant wood and uttering a loud metallic whinnying call.",
    identification_features: "Golden-yellow back and wings contrasting with black rump, vivid scarlet red crest, black-and-white patterned head with prominent eye stripe, speckled throat.",
    conservation_status: "Least Concern (LC)",
    description: "Also known as the Lesser Golden-backed Woodpecker, a vibrant and familiar drummer in subcontinent woodlands and urban parks.",
    image_url: "/species/black-rumped-flameback.jpg",
  },
  "spot-billed-pelican": {
    id: "spot-billed-pelican",
    common_name: "Spot-billed Pelican",
    scientific_name: "Pelecanus philippensis",
    family: "Pelecanidae",
    order_name: "Pelecaniformes",
    habitat_types: ["Wetland", "River/Lake", "Coastal"],
    diet: "Piscivorous (freshwater fish, aquatic amphibians, crustaceans)",
    geographic_distribution: "Southern Asia from peninsular India and Sri Lanka east to Cambodia and Indonesia.",
    ecological_role: "Top-tier aquatic wader regulating fish stocks and indicating waterbody health and unpolluted fishery ecosystems.",
    behavior_notes: "Often hunts cooperatively in semi-circles, beating wings on water to herd schools of fish into shallows before scooping them up in giant gular pouches.",
    identification_features: "Massive waterbird (1.3 m length); predominantly greyish-white plumage, short curly crest on hindneck, massive pinkish bill with a row of distinctive dark spots along the upper mandible and a dull pinkish-purple throat pouch.",
    conservation_status: "Near Threatened (NT)",
    description: "A majestic colonial waterbird that nests in large community heronries atop tall trees near inland freshwater lakes and lagoons.",
    image_url: "/species/spot-billed-pelican.jpg",
  },
  "red-vented-bulbul": {
    id: "red-vented-bulbul",
    common_name: "Red-vented Bulbul",
    scientific_name: "Pycnonotus cafer",
    family: "Pycnonotidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Agricultural", "Forest"],
    diet: "Omnivorous (berries, soft fruits, flower petals, insects)",
    geographic_distribution: "Native to Indian subcontinent; widely introduced across tropical Pacific islands.",
    ecological_role: "Prolific disperser of fruit seeds in secondary scrub and human-modified forest borders.",
    behavior_notes: "Bold, vocal, and inquisitive; makes frequent sallying flights to pluck berries or snap aerial insects.",
    identification_features: "Dark brown body with scale-patterned chest, dark sooty black crested head, distinct white rump, and vivid crimson-red patch beneath the tail vent.",
    conservation_status: "Least Concern (LC)",
    description: "One of the most frequently observed birds in gardens and towns across tropical Asia, famous for its energetic vocalizations.",
    image_url: "/species/red-vented-bulbul.jpg",
  },
  "osprey": {
    id: "osprey",
    common_name: "Osprey",
    scientific_name: "Pandion haliaetus",
    family: "Pandionidae",
    order_name: "Accipitriformes",
    habitat_types: ["River/Lake", "Coastal", "Wetland"],
    diet: "Piscivorous specialist (>99% live fish)",
    geographic_distribution: "Worldwide near large bodies of clean water across all continents except Antarctica.",
    ecological_role: "High-trophic-level bioindicator of aquatic health and heavy metal bioaccumulation.",
    behavior_notes: "Hovers 20-30 meters above water before plunging feet-first, using reversible outer toes and barbed pads to grip slippery prey.",
    identification_features: "Deep brown upperparts, clean white underparts with dark necklace, dark brown mask across white head, long narrow wings angled like an 'M' in flight.",
    conservation_status: "Least Concern (LC)",
    description: "Known as the fish hawk, the Osprey is a master angler with evolutionary adaptations specifically engineered for aquatic plunge-diving.",
    image_url: "/species/osprey.jpg",
  },
  "sarus-crane": {
    id: "sarus-crane",
    common_name: "Sarus Crane",
    scientific_name: "Antigone antigone",
    family: "Gruidae",
    order_name: "Gruiformes",
    habitat_types: ["Wetland", "Agricultural"],
    diet: "Omnivorous (roots, tubers, grain, frogs, aquatic invertebrates, large insects)",
    geographic_distribution: "Plains of northern and central India, Nepal, parts of Indochina, and northern Australia.",
    ecological_role: "Keystone wetland indicator whose presence signifies intact marshland and non-toxic agricultural flooded paddies.",
    behavior_notes: "Mates for life. Pairs perform synchronized bugling unison duets with head arched back and wings drooped in synchronized choreography.",
    identification_features: "Tallest flying bird on Earth (up to 1.8 m tall); uniform dove-grey body, bare crimson-red head and upper neck contrasting with white crown and grey bill.",
    conservation_status: "Vulnerable (VU)",
    description: "The tallest of all flying birds and an emblem of lifelong marital fidelity in Asian cultural lore; vulnerable to wetland draining and power lines.",
    image_url: "/species/sarus-crane.jpg",
  },
  "oriental-magpie-robin": {
    id: "oriental-magpie-robin",
    common_name: "Oriental Magpie-Robin",
    scientific_name: "Copsychus saularis",
    family: "Muscicapidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Forest", "Agricultural"],
    diet: "Insectivorous (ants, beetles, caterpillars, earthworms, crickets)",
    geographic_distribution: "Widely distributed resident across South and Southeast Asia; national bird of Bangladesh.",
    ecological_role: "Ground-foraging insect consumer controlling pest larvae in cultivated soil and lawns.",
    behavior_notes: "Sings melodious, flute-like dawn melodies from conspicuous perches; constantly cocks and fans its tail feathers upward when perching.",
    identification_features: "Male has glossy blue-black upperparts, white belly, and bold white shoulder patch; female is slate-grey where male is black.",
    conservation_status: "Least Concern (LC)",
    description: "A charismatic songbird celebrated for musical virtuosity and confident demeanor around human habitation.",
    image_url: "/species/oriental-magpie-robin.jpg",
  },
  "painted-stork": {
    id: "painted-stork",
    common_name: "Painted Stork",
    scientific_name: "Mycteria leucocephala",
    family: "Ciconiidae",
    order_name: "Ciconiiformes",
    habitat_types: ["Wetland", "River/Lake"],
    diet: "Piscivorous (small fish, frogs, mudskippers, aquatic snakes)",
    geographic_distribution: "Wetlands of the Indian subcontinent and Southeast Asia.",
    ecological_role: "Colonial wading predator that shapes shallow wetland dynamics and cycles organic nutrients at communal nesting heronries.",
    behavior_notes: "Tactile forager: sweeps half-opened bill submerged in murky water, snapping shut in milliseconds when a fish brushes the sensitive bill tip.",
    identification_features: "Large heavy body, heavy yellow downcurved bill, bare orange-yellow face mask, white body with black breast bar, and delicate rose-pink tertial feathers.",
    conservation_status: "Near Threatened (NT)",
    description: "A distinctive broad-winged colonial wading bird that breeds in large communal mixed heronries across protected water bodies.",
    image_url: "/species/painted-stork.jpg",
  },
  "eurasian-spoonbill": {
    id: "eurasian-spoonbill",
    common_name: "Eurasian Spoonbill",
    scientific_name: "Platalea leucorodia",
    family: "Threskiornithidae",
    order_name: "Pelecaniformes",
    habitat_types: ["Wetland", "Coastal", "River/Lake"],
    diet: "Carnivorous (small fish, aquatic insects, shrimp, mollusks, frogs)",
    geographic_distribution: "Shallow wetlands across southern Eurasia, North Africa, and the Indian subcontinent.",
    ecological_role: "Shallow wetland consumer whose sweeping foraging technique stirs benthic nutrients and bioindicates marshland cleanliness.",
    behavior_notes: "Wades slowly through knee-deep water, sweeping its unique spatula-shaped bill side-to-side in a rhythmic scything motion to snap up aquatic organisms by touch.",
    identification_features: "Snow-white plumage with long black legs; distinctive long, flat spoon-shaped black bill with a bright yellow tip; breeding adults display a bushy yellowish-white crest and a yellow breast patch.",
    conservation_status: "Least Concern (LC)",
    description: "An elegant, unmistakable wading bird characterized by its broad spatula-tipped bill and pristine white plumage.",
    image_url: "/species/eurasian-spoonbill.jpg",
  },
  "spotted-owlet": {
    id: "spotted-owlet",
    common_name: "Spotted Owlet",
    scientific_name: "Athene brama",
    family: "Strigidae",
    order_name: "Strigiformes",
    habitat_types: ["Agricultural", "Urban", "Garden"],
    diet: "Insectivorous and carnivorous (beetles, moths, dragonflies, geckos, mice)",
    geographic_distribution: "Tropical South Asia from Iran through India to Southeast Asia.",
    ecological_role: "Nocturnal consumer of crop-eating insects and domestic vermin around suburban habitats.",
    behavior_notes: "Roosts in pairs inside tree hollows or crevices in old brick buildings. When agitated, bobs head up and down comical-fashion while chattering.",
    identification_features: "Small, stocky (21 cm), grayish-brown plumage heavily speckled with white dots, white supercilium eyebrows, piercing golden-yellow iris, no ear tufts.",
    conservation_status: "Least Concern (LC)",
    description: "A familiar companion of old village trees and town avenues, highly tolerant of human proximity.",
    image_url: "/species/spotted-owlet.jpg",
  },
  "indian-roller": {
    id: "indian-roller",
    common_name: "Indian Roller",
    scientific_name: "Coracias benghalensis",
    family: "Coraciidae",
    order_name: "Coraciiformes",
    habitat_types: ["Agricultural", "Grassland", "Garden"],
    diet: "Insectivorous (ground beetles, grasshoppers, crickets, scorpions, small frogs)",
    geographic_distribution: "West Asia across the Indian subcontinent.",
    ecological_role: "Important pest regulator in open farmland and grassland ecosystems.",
    behavior_notes: "Perches conspicuously along roadside wires. Renowned for spectacular aerial courtship tumbling and twisting ('rolling') dives.",
    identification_features: "Dull brownish-olive when perched; explodes in flight into breathtaking flashes of luminous ultramarine and turquoise on wings and tail.",
    conservation_status: "Least Concern (LC)",
    description: "The state bird of several Indian states, famed for the sudden burst of vibrant blues revealed when taking to flight.",
    image_url: "/species/indian-roller.jpg",
  },
  "house-sparrow": {
    id: "house-sparrow",
    common_name: "House Sparrow",
    scientific_name: "Passer domesticus",
    family: "Passeridae",
    order_name: "Passeriformes",
    habitat_types: ["Urban", "Agricultural", "Garden"],
    diet: "Granivorous (grass seeds, cereal grain, breadcrumbs; feed chicks insects)",
    geographic_distribution: "Worldwide commensal species associated with human settlements.",
    ecological_role: "Urban seed consumer and feeder of caterpillar pests to nestlings; critical bellwether of urban architectural greening.",
    behavior_notes: "Communal dust-bathing and chirping, nests under eaves, air-conditioner crevices, and traditional roof tiles.",
    identification_features: "Compact passerine. Male has grey crown, chestnut nape, black bib and bill, warm brown streaked mantle. Female is sandy buff-brown with pale buff eye-stripe.",
    conservation_status: "Least Concern (LC)",
    description: "Once ubiquitous across urban areas, recent declines in modern cities highlight changes in urban building designs and insect food scarcity.",
    image_url: "/species/house-sparrow.jpg",
  },
};
