import { Species } from "../types";

export const LOCAL_SPECIES_CATALOG: Record<string, Species> = {
  "indian-peafowl": {
    id: "indian-peafowl",
    common_name: "Indian Peafowl",
    scientific_name: "Pavo cristatus",
    family: "Phasianidae",
    order_name: "Galliformes",
    habitat_types: ["Forest", "Agricultural", "Garden", "Grassland"],
    diet: "Omnivorous (seeds, insects, fruits, small reptiles, amphibians)",
    geographic_distribution: "Native to the Indian subcontinent; introduced across Europe, Americas, and Australia.",
    ecological_role: "Terrestrial seed disperser and biological pest controller (consuming crop-damaging insects and venomous snakes).",
    behavior_notes: "Ground-foraging, roosts high in canopy trees at dusk. Males engage in dramatic courtship train fanning accompanied by vocal 'may-awe' calls.",
    identification_features: "Male has iridescent electric blue neck and breast, metallic green-bronze eye-spotted train. Female is mottled brown with white throat and pale belly.",
    conservation_status: "Least Concern (LC)",
    description: "The Indian Peafowl is celebrated for its spectacular iridescent plumage and is India's national bird. Highly adaptable to forest edges and cultivated land.",
    image_url: "/species/indian-peafowl.jpg",
  },
  "white-throated-kingfisher": {
    id: "white-throated-kingfisher",
    common_name: "White-throated Kingfisher",
    scientific_name: "Halcyon smyrnensis",
    family: "Alcedinidae",
    order_name: "Coraciiformes",
    habitat_types: ["Wetland", "Agricultural", "River/Lake", "Garden", "Urban"],
    diet: "Carnivorous (small fish, crabs, frogs, lizards, large insects, earthworms)",
    geographic_distribution: "Resident across the Middle East, Indian subcontinent, Indochina, and Philippines.",
    ecological_role: "Mid-tier predator regulating aquatic and terrestrial insect/amphibian populations across agricultural edges.",
    behavior_notes: "Sits motionless on exposed telephone wires or branches overlooking open ground, plunging swiftly down onto prey.",
    identification_features: "Bright chestnut head and belly, bright white throat and breast shield, turquoise-blue back and wings with black patches, massive coral-red dagger bill.",
    conservation_status: "Least Concern (LC)",
    description: "Unlike many kingfishers, this species frequently hunts far from standing water, thriving in open plains, orchards, and urban gardens.",
    image_url: "/species/white-throated-kingfisher.jpg",
  },
  "great-hornbill": {
    id: "great-hornbill",
    common_name: "Great Hornbill",
    scientific_name: "Buceros bicornis",
    family: "Bucerotidae",
    order_name: "Bucerotiformes",
    habitat_types: ["Forest", "Mountain"],
    diet: "Frugivorous primary (figs, wild nutmeg), supplements with small mammals and birds during breeding.",
    geographic_distribution: "Canopy forests of the Western Ghats and Himalayan foothills through Southeast Asia to Sumatra.",
    ecological_role: "Crucial 'farmer of the forest' — primary disperser of large-seeded climax forest tree species.",
    behavior_notes: "Flies with heavy, roaring wingbeats audible from hundreds of meters. Females seal themselves inside tree cavities to nest while males provision them through a narrow slit.",
    identification_features: "Massive yellow bill surmounted by a U-shaped bright yellow-orange casque; black and white wings with broad white tail crossed by subterminal black band.",
    conservation_status: "Vulnerable (VU)",
    description: "One of the largest arboreal birds in Asian tropical rainforests, vulnerable to habitat fragmentation and ancient tree logging.",
    image_url: "/species/great-hornbill.jpg",
  },
  "rose-ringed-parakeet": {
    id: "rose-ringed-parakeet",
    common_name: "Rose-ringed Parakeet",
    scientific_name: "Psittacula krameri",
    family: "Psittaculidae",
    order_name: "Psittaciformes",
    habitat_types: ["Urban", "Agricultural", "Garden", "Forest"],
    diet: "Herbivorous (grain, orchard fruits, berries, nuts, flower buds)",
    geographic_distribution: "Sub-Saharan Africa and Indian subcontinent; widely naturalized in European and American metropolitan parks.",
    ecological_role: "Seed predator and opportunistic flower pollinator; competitor for tree cavity nesting holes.",
    behavior_notes: "Highly gregarious, roosting in noisy communal roosts numbering in thousands, performing rapid arrow-straight flight with high-pitched shriek.",
    identification_features: "Slender emerald-green body with extremely long graduated tail. Adult males exhibit a distinct pink and black neck collar; sharply curved red hooked beak.",
    conservation_status: "Least Concern (LC)",
    description: "A remarkably adaptable psittacine whose intelligence and social cohesion allow it to colonize both rural agricultural belts and bustling urban metropolises.",
    image_url: "/species/rose-ringed-parakeet.jpg",
  },
  "brahminy-kite": {
    id: "brahminy-kite",
    common_name: "Brahminy Kite",
    scientific_name: "Haliastur indus",
    family: "Accipitridae",
    order_name: "Accipitriformes",
    habitat_types: ["Coastal", "Wetland", "River/Lake"],
    diet: "Opportunistic scavenger and predator (carrion, dying fish, crabs, small rodents, insects)",
    geographic_distribution: "Coastal wetlands and estuaries across South Asia, Southeast Asia, and coastal Australia.",
    ecological_role: "Ecosystem scavenger cleaning shoreline debris and regulating estuarine fish and crab mortality.",
    behavior_notes: "Soars along shorelines and harbors with bowed wings, skimming low over tidal flats to seize surface items with talons.",
    identification_features: "Striking contrasting plumage with rich chestnut-red back and wings, immaculate pure white head, neck, and upper breast with fine dark streaks.",
    conservation_status: "Least Concern (LC)",
    description: "A graceful medium raptor often associated with coastal lagoons, mangrove edges, and harbor channels.",
    image_url: "/species/brahminy-kite.jpg",
  },
  "black-crowned-night-heron": {
    id: "black-crowned-night-heron",
    common_name: "Black-crowned Night Heron",
    scientific_name: "Nycticorax nycticorax",
    family: "Ardeidae",
    order_name: "Pelecaniformes",
    habitat_types: ["Wetland", "River/Lake", "Coastal"],
    diet: "Carnivorous (small fish, crustaceans, frogs, aquatic insects, worms)",
    geographic_distribution: "Cosmopolitan wetland resident across North & South America, Europe, Africa, and Asia.",
    ecological_role: "Nocturnal aquatic predator occupying wetland food chains during nighttime when diurnal waders roost.",
    behavior_notes: "Stocky and hunched posture; roosts in dense waterside foliage by day and begins solitary stalking in shallow margins at twilight.",
    identification_features: "Stocky build, black crown and back, pale gray wings and white underparts. Piercing ruby-red eyes, short yellow legs, two long white head plumes during breeding.",
    conservation_status: "Least Concern (LC)",
    description: "A nocturnal ardeid species whose presence indicates healthy riparian reedbeds and functioning wetland ecosystems.",
    image_url: "/species/black-crowned-night-heron.jpg",
  },
  "purple-sunbird": {
    id: "purple-sunbird",
    common_name: "Purple Sunbird",
    scientific_name: "Cinnyris asiaticus",
    family: "Nectariniidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Forest", "Agricultural"],
    diet: "Nectarivore primarily; feeds young on spiders and small caterpillars.",
    geographic_distribution: "Across the Indian subcontinent through Indochina and parts of the Arabian Peninsula.",
    ecological_role: "Vital pollinator for indigenous flowering trees (e.g. Butea monosperma, Erythrina, Woodfordia).",
    behavior_notes: "Hyperactive hovering and darting flight; probes tubular blossoms with downcurved bill while producing rapid buzzing chips.",
    identification_features: "Tiny size (10 cm). Breeding male appears glossy metallic bluish-black with purple sheen and tiny yellow/red pectoral tufts; non-breeding male and female are olive-brown above and pale yellow below.",
    conservation_status: "Least Concern (LC)",
    description: "The Old World ecological equivalent of hummingbirds, indispensable for floral reproduction across arid and garden landscapes.",
    image_url: "/species/purple-sunbird.jpg",
  },
  "barn-owl": {
    id: "barn-owl",
    common_name: "Barn Owl",
    scientific_name: "Tyto alba",
    family: "Tytonidae",
    order_name: "Strigiformes",
    habitat_types: ["Agricultural", "Grassland", "Urban"],
    diet: "Carnivorous (small rodents, shrews, field mice, voles)",
    geographic_distribution: "Found globally across every continent except Antarctica.",
    ecological_role: "Premier biological rodent manager, saving agricultural yields without toxic chemical rodenticides.",
    behavior_notes: "Silent ghost-like flight aided by comb-like serrations on leading flight feathers; asymmetric ear canals permit hunting in complete pitch darkness by sound alone.",
    identification_features: "Distinctive heart-shaped pale facial disc, dark luminous eyes, golden-buff upperparts mottled with delicate grey specks, silky white-to-buff underparts.",
    conservation_status: "Least Concern (LC)",
    description: "A silent nocturnal hunter revered worldwide for pest control yet vulnerable to secondary poisoning from chemical agricultural rodenticides.",
    image_url: "/species/barn-owl.jpg",
  },
  "peregrine-falcon": {
    id: "peregrine-falcon",
    common_name: "Peregrine Falcon",
    scientific_name: "Falco peregrinus",
    family: "Falconidae",
    order_name: "Falconiformes",
    habitat_types: ["Mountain", "Coastal", "Urban"],
    diet: "Specialized avian hunter (pigeons, doves, waterfowl, shorebirds captured in mid-air stoop)",
    geographic_distribution: "Worldwide distribution from Arctic tundra to tropical islands and skyscraper city canyons.",
    ecological_role: "Apex avian pursuit predator maintaining fitness of flocking bird populations.",
    behavior_notes: "Renowned as the fastest animal on Earth, reaching dive (stoop) velocities exceeding 320 km/h (200 mph) to strike aerial prey.",
    identification_features: "Bluish-slate upperparts, dark helmet and pronounced black moustache stripe contrasting with whitish cheeks and barred chest; pointed swept-back wings.",
    conservation_status: "Least Concern (LC)",
    description: "The epitome of speed and aerodynamic engineering, recovered from historical DDT-driven population collapses.",
    image_url: "/species/peregrine-falcon.jpg",
  },
  "black-rumped-flameback": {
    id: "black-rumped-flameback",
    common_name: "Black-rumped Flameback",
    scientific_name: "Dinopium benghalense",
    family: "Picidae",
    order_name: "Piciformes",
    habitat_types: ["Forest", "Garden", "Urban", "Agricultural"],
    diet: "Insectivorous (wood-boring beetle larvae, tree ants, pupae)",
    geographic_distribution: "Widespread resident across Pakistan, India, Bangladesh, and Sri Lanka.",
    ecological_role: "Primary forest health guardian: excises wood-boring pests from mature tree bark and excavates nest cavities reused by secondary cavity dwellers.",
    behavior_notes: "Hops jerkily up tree trunks propped on stiff tail feathers, tapping resonant wood and uttering a loud metallic whinnying call.",
    identification_features: "Golden-yellow back and wings contrasting with black rump, vivid scarlet red crest, black-and-white patterned head with prominent eye stripe, speckled throat.",
    conservation_status: "Least Concern (LC)",
    description: "Also known as the Lesser Golden-backed Woodpecker, a vibrant and familiar drummer in subcontinent woodlands and urban parks.",
    image_url: "/species/black-rumped-flameback.jpg",
  },
  "greater-flamingo": {
    id: "greater-flamingo",
    common_name: "Greater Flamingo",
    scientific_name: "Phoenicopterus roseus",
    family: "Phoenicopteridae",
    order_name: "Phoenicopteriformes",
    habitat_types: ["Coastal", "Wetland"],
    diet: "Filter-feeder (brine shrimp, microscopic algae, diatoms, aquatic insect larvae)",
    geographic_distribution: "Saline mudflats, estuaries, and coastal lagoons in southern Europe, Africa, and coastal South/Southwest Asia.",
    ecological_role: "Keystone benthic filter feeder cycling nutrients in hypersaline lagoons and mudflats.",
    behavior_notes: "Stands on one leg to conserve body heat, feeds with head held upside down in muddy water using specialized lamellae to filter food.",
    identification_features: "Tallest flamingo species (110-150 cm); delicate whitish-pink plumage with carmine wing coverts and black flight feathers; pink bill with black tip.",
    conservation_status: "Least Concern (LC)",
    description: "A magnificent hypersaline wetland specialist whose plumage colour derives from carotenoid pigments in its crustacean and algal diet.",
    image_url: "/species/greater-flamingo.jpg",
  },
  "red-vented-bulbul": {
    id: "red-vented-bulbul",
    common_name: "Red-vented Bulbul",
    scientific_name: "Pycnonotus cafer",
    family: "Pycnonotidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Agricultural", "Forest"],
    diet: "Omnivorous (berries, soft fruits, flower petals, insects)",
    geographic_distribution: "Native to Indian subcontinent; widely introduced across tropical Pacific islands.",
    ecological_role: "Prolific disperser of fruit seeds in secondary scrub and human-modified forest borders.",
    behavior_notes: "Bold, vocal, and inquisitive; makes frequent sallying flights to pluck berries or snap aerial insects.",
    identification_features: "Dark brown body with scale-patterned chest, dark sooty black crested head, distinct white rump, and vivid crimson-red patch beneath the tail vent.",
    conservation_status: "Least Concern (LC)",
    description: "One of the most frequently observed birds in gardens and towns across tropical Asia, famous for its energetic vocalizations.",
    image_url: "/species/red-vented-bulbul.jpg",
  },
  "osprey": {
    id: "osprey",
    common_name: "Osprey",
    scientific_name: "Pandion haliaetus",
    family: "Pandionidae",
    order_name: "Accipitriformes",
    habitat_types: ["River/Lake", "Coastal", "Wetland"],
    diet: "Piscivorous specialist (>99% live fish)",
    geographic_distribution: "Worldwide near large bodies of clean water across all continents except Antarctica.",
    ecological_role: "High-trophic-level bioindicator of aquatic health and heavy metal bioaccumulation.",
    behavior_notes: "Hovers 20-30 meters above water before plunging feet-first, using reversible outer toes and barbed pads to grip slippery prey.",
    identification_features: "Deep brown upperparts, clean white underparts with dark necklace, dark brown mask across white head, long narrow wings angled like an 'M' in flight.",
    conservation_status: "Least Concern (LC)",
    description: "Known as the fish hawk, the Osprey is a master angler with evolutionary adaptations specifically engineered for aquatic plunge-diving.",
    image_url: "/species/osprey.jpg",
  },
  "sarus-crane": {
    id: "sarus-crane",
    common_name: "Sarus Crane",
    scientific_name: "Antigone antigone",
    family: "Gruidae",
    order_name: "Gruiformes",
    habitat_types: ["Wetland", "Agricultural"],
    diet: "Omnivorous (roots, tubers, grain, frogs, aquatic invertebrates, large insects)",
    geographic_distribution: "Plains of northern and central India, Nepal, parts of Indochina, and northern Australia.",
    ecological_role: "Keystone wetland indicator whose presence signifies intact marshland and non-toxic agricultural flooded paddies.",
    behavior_notes: "Mates for life. Pairs perform synchronized bugling unison duets with head arched back and wings drooped in synchronized choreography.",
    identification_features: "Tallest flying bird on Earth (up to 1.8 m tall); uniform dove-grey body, bare crimson-red head and upper neck contrasting with white crown and grey bill.",
    conservation_status: "Vulnerable (VU)",
    description: "The tallest of all flying birds and an emblem of lifelong marital fidelity in Asian cultural lore; vulnerable to wetland draining and power lines.",
    image_url: "/species/sarus-crane.jpg",
  },
  "oriental-magpie-robin": {
    id: "oriental-magpie-robin",
    common_name: "Oriental Magpie-Robin",
    scientific_name: "Copsychus saularis",
    family: "Muscicapidae",
    order_name: "Passeriformes",
    habitat_types: ["Garden", "Urban", "Forest", "Agricultural"],
    diet: "Insectivorous (ants, beetles, caterpillars, earthworms, crickets)",
    geographic_distribution: "Widely distributed resident across South and Southeast Asia; national bird of Bangladesh.",
    ecological_role: "Ground-foraging insect consumer controlling pest larvae in cultivated soil and lawns.",
    behavior_notes: "Sings melodious, flute-like dawn melodies from conspicuous perches; constantly cocks and fans its tail feathers upward when perching.",
    identification_features: "Male has glossy blue-black upperparts, white belly, and bold white shoulder patch; female is slate-grey where male is black.",
    conservation_status: "Least Concern (LC)",
    description: "A charismatic songbird celebrated for musical virtuosity and confident demeanor around human habitation.",
    image_url: "/species/oriental-magpie-robin.jpg",
  },
  "painted-stork": {
    id: "painted-stork",
    common_name: "Painted Stork",
    scientific_name: "Mycteria leucocephala",
    family: "Ciconiidae",
    order_name: "Ciconiiformes",
    habitat_types: ["Wetland", "River/Lake"],
    diet: "Piscivorous (small fish, frogs, mudskippers, aquatic snakes)",
    geographic_distribution: "Wetlands of the Indian subcontinent and Southeast Asia.",
    ecological_role: "Colonial wading predator that shapes shallow wetland dynamics and cycles organic nutrients at communal nesting heronries.",
    behavior_notes: "Tactile forager: sweeps half-opened bill submerged in murky water, snapping shut in milliseconds when a fish brushes the sensitive bill tip.",
    identification_features: "Large heavy body, heavy yellow downcurved bill, bare orange-yellow face mask, white body with black breast bar, and delicate rose-pink tertial feathers.",
    conservation_status: "Near Threatened (NT)",
    description: "A distinctive broad-winged colonial wading bird that breeds in large communal mixed heronries across protected water bodies.",
    image_url: "/species/painted-stork.jpg",
  },
  "common-kingfisher": {
    id: "common-kingfisher",
    common_name: "Common Kingfisher",
    scientific_name: "Alcedo atthis",
    family: "Alcedinidae",
    order_name: "Coraciiformes",
    habitat_types: ["River/Lake", "Wetland", "Coastal"],
    diet: "Piscivorous (minnows, sticklebacks, small aquatic insects)",
    geographic_distribution: "Eurasia, North Africa, and Southeast Asia.",
    ecological_role: "Sensitive bio-indicator bird: presence requires clean, unpolluted, transparent waterways with abundant juvenile fish stocks.",
    behavior_notes: "Darts low over water like a metallic blue arrow; perches quietly on overhanging twigs before executing precision vertical dives.",
    identification_features: "Electric metallic cyan-blue back and crown, rich rufous-orange breast and ear patch, long dagger-like black bill (female has red base on lower mandible).",
    conservation_status: "Least Concern (LC)",
    description: "Small jewel-like river bird whose acute eyesight compensates for underwater refraction when aiming at small swimming fish.",
    image_url: "/species/common-kingfisher.jpg",
  },
  "spotted-owlet": {
    id: "spotted-owlet",
    common_name: "Spotted Owlet",
    scientific_name: "Athene brama",
    family: "Strigidae",
    order_name: "Strigiformes",
    habitat_types: ["Agricultural", "Urban", "Garden"],
    diet: "Insectivorous and carnivorous (beetles, moths, dragonflies, geckos, mice)",
    geographic_distribution: "Tropical South Asia from Iran through India to Southeast Asia.",
    ecological_role: "Nocturnal consumer of crop-eating insects and domestic vermin around suburban habitats.",
    behavior_notes: "Roosts in pairs inside tree hollows or crevices in old brick buildings. When agitated, bobs head up and down comical-fashion while chattering.",
    identification_features: "Small, stocky (21 cm), grayish-brown plumage heavily speckled with white dots, white supercilium eyebrows, piercing golden-yellow iris, no ear tufts.",
    conservation_status: "Least Concern (LC)",
    description: "A familiar companion of old village trees and town avenues, highly tolerant of human proximity.",
    image_url: "/species/spotted-owlet.jpg",
  },
  "indian-roller": {
    id: "indian-roller",
    common_name: "Indian Roller",
    scientific_name: "Coracias benghalensis",
    family: "Coraciidae",
    order_name: "Coraciiformes",
    habitat_types: ["Agricultural", "Grassland", "Garden"],
    diet: "Insectivorous (ground beetles, grasshoppers, crickets, scorpions, small frogs)",
    geographic_distribution: "West Asia across the Indian subcontinent.",
    ecological_role: "Important pest regulator in open farmland and grassland ecosystems.",
    behavior_notes: "Perches conspicuously along roadside wires. Renowned for spectacular aerial courtship tumbling and twisting ('rolling') dives.",
    identification_features: "Dull brownish-olive when perched; explodes in flight into breathtaking flashes of luminous ultramarine and turquoise on wings and tail.",
    conservation_status: "Least Concern (LC)",
    description: "The state bird of several Indian states, famed for the sudden burst of vibrant blues revealed when taking to flight.",
    image_url: "/species/indian-roller.jpg",
  },
  "house-sparrow": {
    id: "house-sparrow",
    common_name: "House Sparrow",
    scientific_name: "Passer domesticus",
    family: "Passeridae",
    order_name: "Passeriformes",
    habitat_types: ["Urban", "Agricultural", "Garden"],
    diet: "Granivorous (grass seeds, cereal grain, breadcrumbs; feed chicks insects)",
    geographic_distribution: "Worldwide commensal species associated with human settlements.",
    ecological_role: "Urban seed consumer and feeder of caterpillar pests to nestlings; critical bellwether of urban architectural greening.",
    behavior_notes: "Communal dust-bathing and chirping, nests under eaves, air-conditioner crevices, and traditional roof tiles.",
    identification_features: "Compact passerine. Male has grey crown, chestnut nape, black bib and bill, warm brown streaked mantle. Female is sandy buff-brown with pale buff eye-stripe.",
    conservation_status: "Least Concern (LC)",
    description: "Once ubiquitous across urban areas, recent declines in modern cities highlight changes in urban building designs and insect food scarcity.",
    image_url: "/species/house-sparrow.jpg",
  },
};
